<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>My Portfolio</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;700&display=swap" rel="stylesheet" />
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Poppins', sans-serif;
      line-height: 1.6;
      background: #f8f9fa;
      color: #333;
    }

    header {
      background: #000;
      color: white;
      padding: 20px 0;
      text-align: center;
    }

    header h1 {
      font-size: 2.5rem;
    }

    nav {
      background: #222;
      display: flex;
      justify-content: center;
      padding: 10px;
    }

    nav a {
      color: #fff;
      text-decoration: none;
      margin: 0 15px;
      font-weight: 500;
      transition: color 0.3s;
    }

    nav a:hover {
      color: #00bcd4;
    }

    section {
      padding: 60px 20px;
      max-width: 1100px;
      margin: auto;
    }

    .about, .projects, .skills, .contact {
      text-align: center;
    }

    .about h2, .projects h2, .skills h2, .contact h2 {
      font-size: 2rem;
      margin-bottom: 20px;
    }

    .projects-container, .skills-container {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 20px;
      margin-top: 30px;
    }

    .project-card, .skill-card {
      background: white;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0,0,0,0.1);
      padding: 20px;
      transition: transform 0.3s;
    }

    .project-card:hover, .skill-card:hover {
      transform: translateY(-5px);
    }

    .skill-card h3 {
      font-size: 1.5rem;
      margin-bottom: 10px;
      color: #00bcd4;
    }

    .skill-card p {
      font-size: 1rem;
      color: #555;
    }

    .contact form {
      max-width: 500px;
      margin: auto;
      text-align: left;
    }

    .contact label {
      display: block;
      margin-top: 15px;
      margin-bottom: 5px;
      font-weight: 500;
    }

    .contact input, .contact textarea {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
    }

    .contact button {
      margin-top: 20px;
      background: #00bcd4;
      border: none;
      color: white;
      padding: 10px 20px;
      border-radius: 5px;
      font-size: 1rem;
      cursor: pointer;
    }

    .contact button:hover {
      background: #0097a7;
    }

    footer {
      background: #111;
      color: white;
      text-align: center;
      padding: 20px;
      margin-top: 40px;
    }

    @media screen and (max-width: 600px) {
      header h1 {
        font-size: 1.8rem;
      }

      nav {
        flex-direction: column;
      }

      nav a {
        margin: 10px 0;
      }
    }
  </style>
</head>
<body>

  <header>
    <h1>Patel Lay</h1>
    <p>Web Developer | Designer | Coder</p>
  </header>

  <nav>
    <a href="#about">About</a>
    <a href="#projects">Projects</a>
    <a href="#skills">Skills</a>
    <a href="#contact">Contact</a>
  </nav>

  <section class="about" id="about">
    <h2>About Me</h2>
    <p>Hello! I'm a passionate web developer who loves creating beautiful and functional websites. I have experience in HTML, CSS, JavaScript, PHP, and more.</p>
  </section>

  <section class="projects" id="projects">
    <h2>My Projects</h2>
    <div class="projects-container">
      <div class="project-card">
        <h3>Portfolio Website</h3>
        <p>A responsive and stylish portfolio built using HTML, CSS, and JS.</p>
      </div>
      <div class="project-card">
        <h3>To-Do App</h3>
        <p>A simple to-do list web app with local storage functionality.</p>
      </div>
      <div class="project-card">
        <h3>Weather App</h3>
        <p>Fetches real-time weather data using a public API.</p>
      </div>
    </div>
  </section>

  <section class="skills" id="skills">
    <h2>My Skills</h2>
    <div class="skills-container">
      <div class="skill-card">
        <h3>HTML5</h3>
        <p>Building semantic and accessible web structures.</p>
      </div>
      <div class="skill-card">
        <h3>CSS3</h3>
        <p>Creating responsive and visually appealing designs.</p>
      </div>
      <div class="skill-card">
        <h3>JavaScript</h3>
        <p>Adding interactivity and dynamic functionality to websites.</p>
      </div>
      <div class="skill-card">
        <h3>PHP</h3>
        <p>Developing server-side applications and dynamic content.</p>
      </div>
    </div>
  </section>

  <section class="contact" id="contact">
    <h2>Contact Me</h2>
    <form id="contactForm">
      <label for="name">Name</label>
      <input type="text" id="name" required />

      <label for="email">Email</label>
      <input type="email" id="email" required />

      <label for="message">Message</label>
      <textarea id="message" rows="5" required></textarea>

      <button type="submit">Send Message</button>
    </form>
  </section>

  <footer>
    <p>© 2025 Patel Lay. All rights reserved.</p>
  </footer>

  <script>
    document.getElementById('contactForm').addEventListener('submit', function(e) {
      e.preventDefault();
      alert('Thank you! Your message has been received.');
      this.reset();
    });
  </script>
</body>
</html>
